### ISSUE TITLE
feature request: update solution to use Amazon Bedrock

### ISSUE THREAD

**Issue by hakanson** [aws-samples/amazon-chime-sdk-call-analytics-real-time-summarizer#16]
The current solution uses a SageMaker deployed `cohere-gpt-medium` model.  Now that Amazon Bedrock is GA, can this be updated to use [Cohere Command on Amazon Bedrock](https://aws.amazon.com/bedrock/cohere-command/)?

Are there model or prompt differences that need to be taken into account?

I'm not sure if supporting both SageMaker and Bedrock options make the most sense, or just replace with the Bedrock solution to minimize potential costs of running an idle SageMaker endpoint.

**Comment by schuettc** [comment]
Upgraded to Bedrock 491defe1fe5c9949a938eaab41a29ff4a09a14d7
